#!/usr/bin/env python3
from pathlib import Path
import argparse
import math
import sys

from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "lib" / "tft_fonts"

CHARS = "".join(chr(i) for i in range(32, 127))

FONT_CANDIDATES = {
    "ui": (
        "assets/fonts/Inter-Regular.ttf",
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/HelveticaNeue.ttc",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
    ),
    "data": (
        "assets/fonts/JetBrainsMono-Regular.ttf",
        "/System/Library/Fonts/SFNSMono.ttf",
        "/System/Library/Fonts/Menlo.ttc",
        "/System/Library/Fonts/Supplemental/Andale Mono.ttf",
    ),
}


def resolve_font(name, override=None):
    candidates = []
    if override:
        candidates.append(override)
    candidates.extend(FONT_CANDIDATES[name])
    for item in candidates:
        path = Path(item)
        if not path.is_absolute():
            path = ROOT / path
        if path.exists():
            return path
    raise SystemExit("No font found for %s" % name)


def pack_nibbles(values):
    out = bytearray()
    it = iter(values)
    for hi in it:
        lo = next(it, 0)
        out.append((hi << 4) | lo)
    return bytes(out)


def render_font(font_path, px):
    font = ImageFont.truetype(str(font_path), px)
    probe = Image.new("L", (4096, 256), 0)
    draw = ImageDraw.Draw(probe)
    global_box = draw.textbbox((0, 0), CHARS, font=font)
    top = global_box[1]
    bottom = global_box[3]
    line_height = max(1, bottom - top)
    glyphs = {}
    pad = 4

    for ch in CHARS:
        adv = int(math.ceil(draw.textlength(ch, font=font)))
        canvas_w = max(adv + (pad * 2), px * 2)
        canvas = Image.new("L", (canvas_w, line_height + (pad * 2)), 0)
        cdraw = ImageDraw.Draw(canvas)
        cdraw.text((pad, pad - top), ch, font=font, fill=255)
        box = canvas.getbbox()
        if box is None:
            glyphs[ch] = (0, 0, 0, 0, max(1, adv), b"")
            continue
        crop = canvas.crop(box)
        values = [min(15, (v + 8) // 17) for v in crop.tobytes()]
        glyphs[ch] = (
            crop.size[0],
            crop.size[1],
            box[0] - pad,
            box[1] - pad,
            max(1, adv),
            pack_nibbles(values),
        )
    return line_height, glyphs


def bytes_literal(data):
    if not data:
        return "b''"
    chunks = []
    raw = "".join("\\x%02x" % b for b in data)
    for i in range(0, len(raw), 64):
        chunks.append("b\"" + raw[i : i + 64] + "\"")
    return " ".join(chunks)


def write_module(path, name, source_font, px, line_height, glyphs):
    lines = [
        "# Generated by firmware/tools/generate_tft_fonts.py",
        "# Source: %s" % source_font,
        "NAME = %r" % name,
        "SIZE = %d" % px,
        "HEIGHT = %d" % line_height,
        "GLYPHS = {",
    ]
    for ch in CHARS:
        gw, gh, xoff, yoff, adv, data = glyphs[ch]
        lines.append("    %r: (%d, %d, %d, %d, %d, %s)," % (ch, gw, gh, xoff, yoff, adv, bytes_literal(data)))
    lines.append("}")
    path.write_text("\n".join(lines) + "\n")


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("--ui-font")
    parser.add_argument("--data-font")
    parser.add_argument("--ui-size", type=int, default=15)
    parser.add_argument("--data-size", type=int, default=30)
    args = parser.parse_args(argv)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, override, px in (
        ("ui", args.ui_font, args.ui_size),
        ("data", args.data_font, args.data_size),
    ):
        font_path = resolve_font(name, override)
        line_height, glyphs = render_font(font_path, px)
        write_module(OUT_DIR / ("%s.py" % name), name, font_path, px, line_height, glyphs)
        print("%s: %s size=%d height=%d glyphs=%d" % (name, font_path, px, line_height, len(glyphs)))


if __name__ == "__main__":
    main(sys.argv[1:])
