"""Add auto_analyse to DeviceToken

Revision ID: a3dc88229df0
Revises: 8f2f9a6f43c1
Create Date: 2026-03-25 00:14:51.993724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3dc88229df0'
down_revision = '8f2f9a6f43c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_analyse', sa.Boolean(), nullable=True))
        
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_column('auto_analyse')

    # ### end Alembic commands ###
