"""Added telemetry fields to DeviceToken

Revision ID: a63e1034816d
Revises: b9d14331bf43
Create Date: 2026-03-11 21:26:22.876053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a63e1034816d'
down_revision = 'b9d14331bf43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_uid', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vbatt_sense', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('storage_sd_free', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_flash_free', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_column('storage_flash_free')
        batch_op.drop_column('storage_sd_free')
        batch_op.drop_column('vbatt_sense')
        batch_op.drop_column('device_uid')

    # ### end Alembic commands ###
