"""Add sync progress fields to DeviceToken

Revision ID: b0806ce78530
Revises: a63e1034816d
Create Date: 2026-03-12 01:43:36.418805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0806ce78530'
down_revision = 'a63e1034816d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_syncing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_sync_filename', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('last_sync_chunk', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_sync_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_column('last_sync_total')
        batch_op.drop_column('last_sync_chunk')
        batch_op.drop_column('last_sync_filename')
        batch_op.drop_column('is_syncing')

    # ### end Alembic commands ###
