"""Added global sync progress fields

Revision ID: dda0ad0a94b2
Revises: f07e0346bf7c
Create Date: 2026-03-18 00:45:02.872366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda0ad0a94b2'
down_revision = 'f07e0346bf7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sync_global_current', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('sync_global_total', sa.BigInteger(), nullable=True))
        batch_op.add_column(sa.Column('sync_total_files', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sync_current_file_index', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_column('sync_current_file_index')
        batch_op.drop_column('sync_total_files')
        batch_op.drop_column('sync_global_total')
        batch_op.drop_column('sync_global_current')

    # ### end Alembic commands ###
