"""add total storage fields to devicetoken

Revision ID: f07e0346bf7c
Revises: b0806ce78530
Create Date: 2026-03-18 00:12:39.947353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f07e0346bf7c'
down_revision = 'b0806ce78530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_sd_total', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('storage_flash_total', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_tokens', schema=None) as batch_op:
        batch_op.drop_column('storage_flash_total')
        batch_op.drop_column('storage_sd_total')

    # ### end Alembic commands ###
