#!/usr/bin/env python3
from pathlib import Path
import argparse
import sys

from PIL import Image, ImageEnhance


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "lib" / "tft_boot_logo.py"
RAW_OUT = ROOT / "lib" / "tft_boot_logo.raw"


def rgb565_bytes(img):
    out = bytearray()
    data = img.convert("RGB").tobytes()
    for i in range(0, len(data), 3):
        r = data[i]
        g = data[i + 1]
        b = data[i + 2]
        value = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
        # Store panel/SPI byte order directly. This bypasses framebuf.show().
        out.append((value >> 8) & 0xFF)
        out.append(value & 0xFF)
    return bytes(out)


def main(argv):
    parser = argparse.ArgumentParser()
    parser.add_argument("source")
    parser.add_argument("--width", type=int, default=304)
    parser.add_argument("--max-height", type=int, default=160)
    parser.add_argument("--contrast", type=float, default=1.12)
    parser.add_argument("--brightness", type=float, default=1.05)
    args = parser.parse_args(argv)

    src = Image.open(args.source).convert("RGBA")
    src.thumbnail((args.width, args.max_height), Image.Resampling.LANCZOS)

    # Composite over black so the actual provided artwork, including glow and
    # dark backdrop, is preserved instead of becoming a thresholded silhouette.
    bg = Image.new("RGBA", src.size, (0, 0, 0, 255))
    bg.alpha_composite(src)
    img = bg.convert("RGB")
    img = ImageEnhance.Contrast(img).enhance(args.contrast)
    img = ImageEnhance.Brightness(img).enhance(args.brightness)

    raw = rgb565_bytes(img)
    RAW_OUT.write_bytes(raw)
    OUT.write_text(
        "\n".join(
            (
                "# Generated by firmware/tools/generate_tft_boot_logo.py",
                "# Source: %s" % Path(args.source),
                "BOOT_LOGO_W = %d" % img.width,
                "BOOT_LOGO_H = %d" % img.height,
                "BOOT_LOGO_PATH = '/lib/tft_boot_logo.raw'",
                "",
            )
        )
    )
    print("wrote %s and %s %dx%d %d bytes" % (OUT, RAW_OUT, img.width, img.height, len(raw)))


if __name__ == "__main__":
    main(sys.argv[1:])
